CLEANUP_IDNAME = "mesh.clean_mesh_operator"
CLEANUP_LABEL = "Clean selection"
CLEANUP_PANEL_IDNAME = "MESH_PT_clean"
CLEANUP_PANEL_LABEL = "Mesh Pre-Processing"

SLICE_IDNAME = "mesh.mesh_slicer_operator"
SLICE_LABEL = "Slice selection"
SLICE_PANEL_IDNAME = "MESH_PT_slice"
SLICE_PANEL_LABEL = "Mesh Slicing"

LOD_IDNAME = "mesh.lod_gen_operator"
LOD_LABEL = "Create LODs"
LOD_PANEL_IDNAME = "MESH_PT_lod"
LOD_PANEL_LABEL = "LOD Creation"

UNWRAP_IDNAME = "mesh.xatlas_unwrap_operator"
UNWRAP_LABEL = "Unwrap (xAtlas)"
UNWRAP_PANEL_IDNAME = "MESH_PT_xatlas_unwrap"
UNWRAP_PANEL_LABEL = "xAtlas Unwrapping"

BAKE_IDNAME = "mesh.multi_bake_operator"
BAKE_LABEL = "Bake selection"
BAKE_PANEL_IDNAME = "MESH_PT_bake"
BAKE_PANEL_LABEL = "Texture Transfer"
BAKE_SETTINGS_IDNAME = "prop.bake_settings"

COMB_IDNAME = "mesh.terrestrial_lod_gen_operator"
COMB_LABEL = "Run Pipeline"
COMB_PANEL_IDNAME = "MESH_PT_terrestrial_lod"
COMB_PANEL_LABEL = "Combined Pipeline"
