CLEANUP_IDNAME = "mesh.clean_mesh_operator"
CLEANUP_LABEL = "Cleans the selected mesh."
CLEANUP_PANEL_IDNAME = "MESH_PT_clean"
CLEANUP_PANEL_LABEL = "Clean Mesh Panel"

SLICE_IDNAME = "mesh.mesh_slicer_operator"
SLICE_LABEL = "Slices the selected mesh."
SLICE_PANEL_IDNAME = "MESH_PT_slice"
SLICE_PANEL_LABEL = "Slices the selected mesh."

LOD_IDNAME = "mesh.lod_gen_operator"
LOD_LABEL = "Creates LODs of the selected mesh, sorted into groups, using the Bake Settings"
LOD_PANEL_IDNAME = "MESH_PT_lod"
LOD_PANEL_LABEL = "Creates LODs of the selected mesh, sorted into groups, using the Bake Settings"

UNWRAP_IDNAME = "mesh.xatlas_unwrap_operator"
UNWRAP_LABEL = "Unwraps the selected Mesh using xAtlas."
UNWRAP_PANEL_IDNAME = "MESH_PT_xatlas_unwrap"
UNWRAP_PANEL_LABEL = "Unwraps the selected Mesh using xAtlas."

BAKE_IDNAME = "mesh.multi_bake_operator"
BAKE_LABEL = "Bakes the selected meshes using a single highpoly reference."
BAKE_PANEL_IDNAME = "MESH_PT_bake"
BAKE_PANEL_LABEL = "Bakes the selected meshes using a single highpoly reference."
BAKE_SETTINGS_IDNAME = "prop.bake_settings"

COMB_IDNAME = "mesh.terrestrial_lod_gen_operator"
COMB_LABEL = "Generates LOD steps for the defined mesh."
COMB_PANEL_IDNAME = "MESH_PT_terrestrial_lod"
COMB_PANEL_LABEL = "Generates LOD steps for the defined mesh."
